-- MySQL Script generated by MySQL Workbench
-- 11/13/16 11:54:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema persona
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema persona
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `persona` DEFAULT CHARACTER SET utf8 ;
USE `persona` ;

-- -----------------------------------------------------
-- Table `persona`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persona`.`alumno` (
  `dni` INT NOT NULL,
  `apyn` VARCHAR(30) NULL,
  `fec_nac` DATE NULL,
  `sexo` CHAR(1) NULL,
  `fec_ing` DATE NULL,
  `mat_aprob` INT NULL,
  `promedio` DOUBLE NULL,
  `carrera` VARCHAR(3) NULL,
  PRIMARY KEY (`dni`),
  UNIQUE INDEX `dni` (`dni` ASC))
ENGINE = EXAMPLE
PACK_KEYS = 1;

CREATE USER 'root' IDENTIFIED BY 'prisma';

GRANT ALL ON `persona`.* TO 'root';
GRANT SELECT, INSERT, TRIGGER ON TABLE `persona`.* TO 'root';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `persona`.* TO 'root';
GRANT EXECUTE ON ROUTINE `persona`.* TO 'root';
GRANT SELECT ON TABLE `persona`.* TO 'root';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
